---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksworkshop-eksctl
  region: eu-west-1

managedNodeGroups:
- name: nodegroup
  instanceType: t3a.small
  desiredCapacity: 3
  iam:
    withAddonPolicies:
      albIngress: true

secretsEncryption:
  keyARN: arn:aws:kms:eu-west-1:216462449154:key/8d994ad0-dd11-483f-be8e-ed60c289f8b3
